on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - '**'
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Run a yarn or npm command
      # You may pin to the exact commit or the version.
      # uses: Adzz/yarn_command_action@56ed36b86d715869a3cf3d2a9b2de2aff7fa945e
      uses: Adzz/yarn_command_action@v1.0.0
      with:
        # Specify whether to use npm or yarn to run the tests. May be npm or yarn only defaults to yarn
        package-manager: yarn
        # The command you wish to run e.g. test
        command: test-coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
